Remove HasBits<> ctor with empty initializer list expectation.
This results in a nullptr dereference which is UB.

Cherry picked from https://github.com/protocolbuffers/protobuf/commit/5acc4899205ca70eea650c9b40f0bbbeaa901596.

It's to fix a build error when doing clang update:
external/protobuf/src/google/protobuf/has_bits_test.cc:66:26: error: constexpr variable 'bits' must be initialized by a constant expression
   66 |     constexpr HasBits<4> bits({});
      |                          ^~~~~~~~
external/protobuf/src/google/protobuf/has_bits.h:36:22: note: dereferencing a null pointer is not allowed in a constant expression
   36 |     Copy(has_bits_, &*has_bits.begin(), has_bits.size());
      |                      ^
external/protobuf/src/google/protobuf/has_bits_test.cc:66:26: note: in call to 'HasBits({nullptr, 0})'
   66 |     constexpr HasBits<4> bits({});
      |                          ^~~~~~~~
1 error generated.

PiperOrigin-RevId: 789334889
Bug: 458484727
Test: build
Change-Id: I9bc8aacfb2cf7b8cd08a9b15c4dd95148b5d4f54